# Site settings
# Meta tags
title: Grantmakers.io - A Community Project
description: Quickly find data on 82,000 grantmaking institutions in the US. An open source project from your friends at SmarterGiving.

# Jekyll settings
baseurl: # Leave this blank unless your site is located on a subpath, e.g. /blog
url: https://www.grantmakers.io # Typically http://www.yourdomain.org
sass:
  sass_dir: assets/css/_sass

# Google Analytics
google_analytics: UA-84268197-1

# Algolia Link
algolia_link: http://goto.algolia.com/l/139121/2017-10-24/26gc84

# Sitewide helpers
last_updated: '2018-12-26T15:26:19.475Z'

number_of_filings: 368312
number_of_foundations: 82869
number_of_grants: 4617256

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - scripts/
  - data/ #Note: does not affect _data folder